<?php

return [
    'messages' => [
        'passwords-sent'   => 'Hemos enviado por correo electrónico el enlace para restablecer su contraseña.',
        'error-email'      => 'El correo electrónico proporcionado, no corresponde a uno válido.',
        'error-phone'      => 'El número de celular proporcionado, no corresponde a uno válido.',
        'form-empty'       => 'Se han encontrado campos vacíos en el formulario. Por favor, llenarlos.',
        'uuid-not-found'   => 'Ha ocurrido un problema al consultar la información solicitada.',
        'login-success'    => 'Credenciales de acceso correctas. ¡Bienvenido!',
        'logout-success'   => 'La sesión ha expirado. ¡Adiós!',
        'get-success'      => 'Se ha obtenido la información correctamente.',
        'update-success'   => 'Se ha realizado la actualización correctamente.',
        'register-success' => 'Se ha realizado el registro correctamente.',
        'delete-success'   => 'Se ha realizado el borrado correctamente.',
        'get-error'        => 'Ha ocurrido un problema al obtener la información solicitada.',
        'update-error'     => 'Ha ocurrido un problema con la actualización.',
        'register-error'   => 'Ha ocurrido un problema con el registro.',
        'delete-error'     => 'Ha ocurrido un problema con el borrado.',
        'image-error'      => 'Ha ocurrido un problema con el regstro de la imagen.',
        'name_required'              => 'El nombre es obligatorio.',
        'name_string'                => 'El nombre debe ser una cadena de texto.',
        'name_max'                   => 'El nombre no puede tener más de 255 caracteres.',
        'email_required'             => 'El correo electrónico es obligatorio.',
        'email_email'                => 'Debe ser una dirección de correo electrónico válida.',
        'email_max'                  => 'El correo electrónico no puede tener más de 255 caracteres.',
        'email_unique'               => 'El correo electrónico ya está en uso.',
        'current_password_min'       => 'La contraseña actual debe tener al menos 8 caracteres.',
        'current_password_regex'     => 'La contraseña actual debe contener al menos una letra minúscula, una letra mayúscula y un número.',
        'current_password_required'  => 'La contraseña actual es obligatoria.',
        'current_password_incorrect' => 'La contraseña actual no es correcta.',
        'password_required'          => 'La nueva contraseña es obligatoria.',
        'password_min'               => 'La nueva contraseña debe tener al menos 8 caracteres.',
        'password_regex'             => 'La nueva contraseña debe contener al menos una letra minúscula, una letra mayúscula y un número.',
        'password_confirmed'         => 'La confirmación de la contraseña no coincide.',
        'error'            => 'El servidor encontró un error inesperado. Por favor, inténtalo de nuevo más tarde.',
    ]
];
